name: "bluebell"
mode: "dev"
port: 8081
version: "v0.0.1"
log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "118.195.180.99"
  port: 3306
  user: "root"
  password: "chon159213"
  dbname: "test"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "118.195.180.99"
  port: 6379
  password: "chon159213"
  db: 0
  pool_size: 100



